"""Public package exports for DeepSeek Runtime."""

from .approval import (
    ApprovalOutcome,
    ApprovalProvider,
    ApprovalRequest,
    AuthorizationEvent,
    AuthorizationSession,
    summarize_approval,
)
from .change_journal import ChangeJournalStore, default_change_journal_dir, workspace_identity
from .client import DeepSeekClient, ProviderResult, RuntimeSettings
from .contracts import (
    ChangeJournalEntry,
    ContractViolation,
    ErrorCode,
    JournalFileRecord,
    OperatorAction,
    PublishableEvidence,
    ReceiptRequirement,
    RecoverableCheckpoint,
    RecoveryPolicy,
    RollbackHandle,
    RuntimeErrorInfo,
    RuntimeState,
    ToolArgumentError,
    ToolCallCheckpoint,
    ToolRegistry,
    ToolResultError,
    ToolSpec,
    TransitionRule,
    normalize_tool_result,
    transition_manifest,
    validate_transition,
)
from .diagnostics import build_diagnostics
from .observability import summarize_observability
from .runtime import DeepSeekRuntime, RuntimeResult, WorkspaceTools
from .security import (
    ChangeManager,
    ChangeSet,
    Decision,
    FileChange,
    PermissionPolicy,
    PermissionRequest,
    PermissionRule,
    Risk,
    RollbackToken,
    WorkspaceSandbox,
    content_sha256,
)
from .session import (
    SessionState,
    ToolCallRecord,
    ToolExecutionResult,
    reconcile_tool_call,
    resume_tool_calls,
)
from .workspace import WorkspaceResolver, WorkspaceViolation

__version__ = "0.1.1a1"

__all__ = [
    "__version__",
    "ApprovalOutcome",
    "ApprovalProvider",
    "ApprovalRequest",
    "AuthorizationEvent",
    "AuthorizationSession",
    "ChangeJournalEntry",
    "ChangeJournalStore",
    "ChangeManager",
    "ChangeSet",
    "ContractViolation",
    "DeepSeekClient",
    "DeepSeekRuntime",
    "Decision",
    "ErrorCode",
    "FileChange",
    "JournalFileRecord",
    "OperatorAction",
    "PermissionPolicy",
    "PermissionRequest",
    "PermissionRule",
    "ProviderResult",
    "PublishableEvidence",
    "ReceiptRequirement",
    "RecoverableCheckpoint",
    "RecoveryPolicy",
    "Risk",
    "RollbackHandle",
    "RollbackToken",
    "RuntimeErrorInfo",
    "RuntimeResult",
    "RuntimeSettings",
    "RuntimeState",
    "SessionState",
    "ToolArgumentError",
    "ToolCallRecord",
    "ToolExecutionResult",
    "ToolCallCheckpoint",
    "ToolRegistry",
    "ToolResultError",
    "ToolSpec",
    "TransitionRule",
    "WorkspaceResolver",
    "WorkspaceSandbox",
    "WorkspaceViolation",
    "WorkspaceTools",
    "build_diagnostics",
    "content_sha256",
    "default_change_journal_dir",
    "normalize_tool_result",
    "reconcile_tool_call",
    "resume_tool_calls",
    "summarize_approval",
    "summarize_observability",
    "transition_manifest",
    "validate_transition",
    "workspace_identity",
]
